// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd89NWYTFvXf9Ai-8cgyAT2l5xQxB2pYk',
    appId: '1:640087565519:web:598011bb218d62533943ba',
    messagingSenderId: '640087565519',
    projectId: 'song-learn-flutter',
    authDomain: 'song-learn-flutter.firebaseapp.com',
    storageBucket: 'song-learn-flutter.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDA4O-TFuJnJ_kxTfELrvatNxx0fzFUZ0k',
    appId: '1:640087565519:android:513f3c09545e32923943ba',
    messagingSenderId: '640087565519',
    projectId: 'song-learn-flutter',
    storageBucket: 'song-learn-flutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBh59pl3hIzj7GMtsL3dSHxVhYMrFSMi6E',
    appId: '1:640087565519:ios:a5418ecde78164eb3943ba',
    messagingSenderId: '640087565519',
    projectId: 'song-learn-flutter',
    storageBucket: 'song-learn-flutter.appspot.com',
    iosBundleId: 'com.example.songlearn',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBh59pl3hIzj7GMtsL3dSHxVhYMrFSMi6E',
    appId: '1:640087565519:ios:b504c98143813e9d3943ba',
    messagingSenderId: '640087565519',
    projectId: 'song-learn-flutter',
    storageBucket: 'song-learn-flutter.appspot.com',
    iosBundleId: 'com.example.songlearn.RunnerTests',
  );
}
